#!/usr/bin/env bash
#install and setup haproxy on an ubuntu machine

#Update package list and install haproxy
apt-get update
apt-get -y install haproxy

#enable haproxy init script

#configure the haproxy to forward requests to my two servers using the round-robin algorithm
echo "
#my config
frontend web-frontend
        mode tcp
	bind *:80
	default_backend web-backend
backend web-backend
        balance roundrobin
	server 117930-web-01 18.233.62.82:80 check
	server 117930-web-02 107.22.146.46:80 check
" >> /etc/haproxy/haproxy.cfg
#restart haproxy
service haproxy restart
