#!/bin/bash
# Get the PID of the master process
MASTER_PID=$(ps aux | grep gunicorn | grep master | awk '{print $2}')
# Send the HUP signal to the master to reload gracefully
kill -HUP $MASTER_PID
# Wait for the reload to complete
sleep 10
# Check the status of Gunicorn
systemctl status gunicorn

